[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

[nixpacks]
nixPkgs = ["gcc", "python39", "python39Packages.pip"]
